### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by mateosilguero** [leanflutter/flipper-plugin-reduxinspector#1]
This plugin should work on React Native app ?

I can see the plugin installed, but not on the side menu

<img width="1251" alt="Captura de pantalla 2019-10-08 a la(s) 23 18 22" src="https://user-images.githubusercontent.com/25598400/66446708-0d091f00-ea22-11e9-8f3b-296a9ae5d1df.png">

(Redux inspector works fine in react-native-debugger app)

**Comment by lijy91** [comment]
This plugin only supports flutter (via [flutter_flipperkit](https://github.com/blankapp/flutter_flipperkit)) and does not support react native

**Comment by zrg-team** [comment]
@mateosilguero 
you can u it instead. It support react-native
https://github.com/zrg-team/rn-redux-middleware-flipper

**Comment by mateosilguero** [comment]
Thanks ! its awesome 👏
