### ISSUE TITLE
Plugin name mismatch: Package 'flipper-plugin-reduxinspector' exposed a plugin with id 'ReduxInspector'. Please update the 'package.json' to match the exposed plugin id

### ISSUE THREAD

**Issue by aamnah** [leanflutter/flipper-plugin-reduxinspector#4]
Getting `Plugin name mismatch: Package 'flipper-plugin-reduxinspector' exposed a plugin with id 'ReduxInspector'. Please update the 'package.json' to match the exposed plugin id` 

Flipper (0.82.1)

![Screenshot from 2021-03-29 12-24-06](https://user-images.githubusercontent.com/1043670/112800933-be25ce00-9089-11eb-88ae-3fcb7f6baac7.png)

**Comment by lijy91** [comment]
Updated to `1.0.4`
